import { Product } from '@/pageComponents/Nftea/globalTypes';

export const products: Product[] = [
  //#region coffee
  {
    id: 'coffee-0',
    name: 'COLD BREW CARAMEL',
    description: 'Кофе, солёная карамель, кофейная спума',
    img: {
      lid: '/nftea/img/cups/cold-brew-caramel/lid.png',
      cup: '/nftea/img/cups/cold-brew-caramel/cup.png',
      type: 0,
    },
    type: 'coffee',
    volume: 350,
    price: 400,
  },
  {
    id: 'coffee-1',
    name: 'BANANA DALGONA',
    description: 'Взбитый кофе, банановое молоко, тапиока',
    img: {
      lid: '/nftea/img/cups/banana-dalgona/lid.png',
      cup: '/nftea/img/cups/banana-dalgona/cup.png',
      type: 0,
    },
    type: 'coffee',
    volume: 350,
    price: 400,
  },
  {
    id: 'coffee-2',
    name: 'BERRY FRAPPUCCINO',
    description: 'Кофе, пломбир, ягодное печенье',
    img: {
      lid: '/nftea/img/cups/berry-frappuccino/lid.png',
      cup: '/nftea/img/cups/berry-frappuccino/cup.png',
      type: 0,
    },
    type: 'coffee',
    volume: 350,
    price: 400,
  },
  {
    id: 'coffee-3',
    name: 'TROPICAL BUMBLE',
    description: 'Кофе, маракуйя, манговая спума',
    img: {
      lid: '/nftea/img/cups/tropical-bumble/lid.png',
      cup: '/nftea/img/cups/tropical-bumble/cup.png',
      type: 0,
    },
    type: 'coffee',
    volume: 350,
    price: 400,
  },
  {
    id: 'coffee-4',
    name: 'BLACK TONIC',
    description: 'Кофе, тоник, лемонграсс',
    img: {
      lid: '/nftea/img/cups/black-tonic/lid.png',
      cup: '/nftea/img/cups/black-tonic/cup.png',
      type: 0,
    },
    type: 'coffee',
    volume: 350,
    price: 400,
  },
  //#endregion
  //#region tea
  {
    id: 'tea-0',
    name: 'MELONY',
    description: 'Улун, клубника, дыня',
    img: {
      lid: '/nftea/img/cups/melony/lid.png',
      cup: '/nftea/img/cups/melony/cup.png',
      type: 1,
    },
    type: 'tea',
    volume: 500,
    price: 550,
  },
  {
    id: 'tea-1',
    name: 'MAX FRUIT',
    description:
      'Жасмин, апельсин, грейпфрут, лайм, ананас, маракуйя, личи, клубника',
    img: {
      lid: '/nftea/img/cups/max-fruit/lid.png',
      cup: '/nftea/img/cups/max-fruit/cup.png',
      type: 1,
    },
    type: 'tea',
    volume: 500,
    price: 600,
  },
  {
    id: 'tea-3',
    name: 'CHERRY BERRY',
    description: 'Да хун пао, вишня, миндаль',
    img: {
      lid: '/nftea/img/cups/cherry-berry/lid.png',
      cup: '/nftea/img/cups/cherry-berry/cup.png',
      type: 1,
    },
    type: 'tea',
    volume: 500,
    price: 500,
  },
  {
    id: 'tea-4',
    name: 'G FRUIT',
    description: 'Бергамот, грейпфрут, бузина',
    img: {
      lid: '/nftea/img/cups/g-fruit/lid.png',
      cup: '/nftea/img/cups/g-fruit/cup.png',
      type: 1,
    },
    type: 'tea',
    volume: 500,
    price: 500,
  },
  {
    id: 'tea-5',
    name: 'RED BERRY',
    description: 'Жасмин, малина, манговая спума',
    img: {
      lid: '/nftea/img/cups/red-berry/lid.png',
      cup: '/nftea/img/cups/red-berry/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 550,
  },
  {
    id: 'tea-6',
    name: 'PEACH BEACH',
    description: 'Улун, персик, грейпфрут, сырная спума',
    img: {
      lid: '/nftea/img/cups/peach-beach/lid.png',
      cup: '/nftea/img/cups/peach-beach/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 600,
  },
  {
    id: 'tea-7',
    name: 'MANGO PAO',
    description: 'Да хун пао, манго, мёд, кокосовая спума',
    img: {
      lid: '/nftea/img/cups/mango-pao/lid.png',
      cup: '/nftea/img/cups/mango-pao/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 600,
  },
  {
    id: 'tea-8',
    name: 'BLACK BERRY',
    description: 'Бергамот, ежевика, смородина, сырная спума',
    img: {
      lid: '/nftea/img/cups/black-berry/lid.png',
      cup: '/nftea/img/cups/black-berry/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 600,
  },
  {
    id: 'tea-9',
    name: 'TRIPLE GREEN',
    description: 'Матча, киви, эстрагон, кокосовая спума',
    img: {
      lid: '/nftea/img/cups/triple-green/lid.png',
      cup: '/nftea/img/cups/triple-green/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 600,
  },
  {
    id: 'tea-10',
    name: 'JASMINE',
    description: 'Тай жасмин, манговая спума',
    img: {
      lid: '/nftea/img/cups/jasmine/lid.png',
      cup: '/nftea/img/cups/jasmine/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 400,
  },
  {
    id: 'tea-11',
    name: 'OOLONG',
    description: 'Милк улун, сырная спума',
    img: {
      lid: '/nftea/img/cups/oolong/lid.png',
      cup: '/nftea/img/cups/oolong/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 400,
  },
  {
    id: 'tea-12',
    name: 'DA HONG PAO',
    description: 'Да хун пао, манговая спума',
    img: {
      lid: '/nftea/img/cups/da-hong-pao/lid.png',
      cup: '/nftea/img/cups/da-hong-pao/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 400,
  },
  {
    id: 'tea-13',
    name: 'BERGAMOT',
    description: 'Бергамот, сырная спума',
    img: {
      lid: '/nftea/img/cups/bergamot/lid.png',
      cup: '/nftea/img/cups/bergamot/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 400,
  },
  {
    id: 'tea-14',
    name: 'MATCHA',
    description: 'Матча, кокосовая спума',
    img: {
      lid: '/nftea/img/cups/matcha/lid.png',
      cup: '/nftea/img/cups/matcha/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 400,
  },
  {
    id: 'tea-15',
    name: 'THAI ALOE',
    description: 'Тай Чай, алое, молоко, тапиока',
    img: {
      lid: '/nftea/img/cups/thai-aloe/lid.png',
      cup: '/nftea/img/cups/thai-aloe/cup.png',
      type: 0,
    },
    type: 'tea',
    volume: 350,
    price: 450,
  },
  {
    id: 'tea-16',
    name: 'THAI PEACHY',
    description: 'Тай Чай, персик, молоко, тапиока',
    img: {
      lid: '/nftea/img/cups/thai-peachy/lid.png',
      cup: '/nftea/img/cups/thai-peachy/cup.png',
      type: 0,
    },
    type: 'tea',
    volume: 350,
    price: 400,
  },
  {
    id: 'tea-17',
    name: 'THAI BARBERRY',
    description: 'Тай Чай, барбарис, молоко, тапиока',
    img: {
      lid: '/nftea/img/cups/thai-barberry/lid.png',
      cup: '/nftea/img/cups/thai-barberry/cup.png',
      type: 0,
    },
    type: 'tea',
    volume: 350,
    price: 450,
  },
  {
    id: 'tea-18',
    name: 'MANGO CARAMEL',
    description: 'Йогурт, манго, карамель, чиа',
    img: {
      lid: '/nftea/img/cups/mango-caramel/lid.png',
      cup: '/nftea/img/cups/mango-caramel/cup.png',
      type: 0,
    },
    type: 'tea',
    volume: 350,
    price: 450,
  },
  {
    id: 'tea-19',
    name: 'COCO RASPBERRY',
    description: 'Йогурт, малина, кокос, чиа',
    img: {
      lid: '/nftea/img/cups/coco-raspberry/lid.png',
      cup: '/nftea/img/cups/coco-raspberry/cup.png',
      type: 0,
    },
    type: 'tea',
    volume: 350,
    price: 450,
  },
  {
    id: 'tea-20',
    name: 'MANGO LYCHEE',
    description: 'Жасмин, манго, личи',
    img: {
      lid: '/nftea/img/cups/mango-lychee/lid.png',
      cup: '/nftea/img/cups/mango-lychee/cup.png',
      type: 1,
    },
    type: 'tea',
    volume: 500,
    price: 550,
  },
  {
    id: 'tea-21',
    name: 'MILK OOLONG',
    description: 'Сливочный ирис, миндаль, халва',
    img: {
      lid: '/nftea/img/cups/milk-oolong/lid.png',
      cup: '/nftea/img/cups/milk-oolong/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 300,
  },
  {
    id: 'tea-22',
    name: 'THAI JASMINE',
    description: 'Жасмин, ананас, лемонграсс',
    img: {
      lid: '/nftea/img/cups/thai-jasmine/lid.png',
      cup: '/nftea/img/cups/thai-jasmine/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 300,
  },
  {
    id: 'tea-23',
    name: 'DA HONG PAO',
    description: 'Ореховая карамель, мёд, лаванда',
    img: {
      lid: '/nftea/img/cups/da-hong-pao-1/lid.png',
      cup: '/nftea/img/cups/da-hong-pao-1/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 300,
  },
  {
    id: 'tea-24',
    name: 'BERGAMOT',
    description: 'Бергамот, лайм, зизифора',
    img: {
      lid: '/nftea/img/cups/bergamot-1/lid.png',
      cup: '/nftea/img/cups/bergamot-1/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 300,
  },
  {
    id: 'tea-25',
    name: 'MATCHA',
    description: 'Матча, опунция, лист лайма',
    img: {
      lid: '/nftea/img/cups/matcha-1/lid.png',
      cup: '/nftea/img/cups/matcha-1/cup.png',
      type: 3,
    },
    type: 'tea',
    volume: 450,
    price: 300,
  },
  //#endregion
  //#region
  {
    id: 'beverage-0',
    name: 'LEMON CELLO',
    description: 'Лимон, лайм, апельсин',
    img: {
      lid: '/nftea/img/cups/lemon-cello/lid.png',
      cup: '/nftea/img/cups/lemon-cello/cup.png',
      type: 2,
    },
    type: 'beverage',
    volume: 550,
    price: 400,
  },
  {
    id: 'beverage-1',
    name: 'MANGO PASSION',
    description: 'Манго, маракуйя',
    img: {
      lid: '/nftea/img/cups/mango-passion/lid.png',
      cup: '/nftea/img/cups/mango-passion/cup.png',
      type: 2,
    },
    type: 'beverage',
    volume: 550,
    price: 400,
  },
  {
    id: 'beverage-2',
    name: 'BASIL FRESH',
    description: 'Базилик, фейхоа, лайм',
    img: {
      lid: '/nftea/img/cups/basil-fresh/lid.png',
      cup: '/nftea/img/cups/basil-fresh/cup.png',
      type: 2,
    },
    type: 'beverage',
    volume: 550,
    price: 400,
  },
  {
    id: 'beverage-3',
    name: 'RED GINGER',
    description: 'Малина, имбирь',
    img: {
      lid: '/nftea/img/cups/red-ginger/lid.png',
      cup: '/nftea/img/cups/red-ginger/cup.png',
      type: 2,
    },
    type: 'beverage',
    volume: 550,
    price: 400,
  },
  {
    id: 'beverage-4',
    name: 'PINK PINEAPPLE',
    description: 'Ананас, грейпфут',
    img: {
      lid: '/nftea/img/cups/pink-pineapple/lid.png',
      cup: '/nftea/img/cups/pink-pineapple/cup.png',
      type: 2,
    },
    type: 'beverage',
    volume: 550,
    price: 400,
  },
  {
    id: 'beverage-5',
    name: 'SECRET INFINITI',
    description: '-',
    img: {
      lid: '/nftea/img/cups/secret-infiniti/lid.png',
      cup: '/nftea/img/cups/secret-infiniti/cup.png',
      type: 3,
    },
    type: 'beverage',
    volume: null,
    price: null,
  },
  //#endregion
];
